#
# IMPORTANT NOTE
#
# This chart inherits from k8s-at-home common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: obebete/winbox
  # -- image tag
  # @default -- chart.appVersion
  tag: 
  # -- image pull policy
  pullPolicy: Always

# -- environment variables. See more environment variables in the [winbox documentation](https://winbox.org/docs).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  # -- HTTP password (user is always `kasm_user`)
  VNC_PW: password
  # -- Set debug mode
  KASM_DEBUG: 1

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 6901

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false
    annotations: {}
    hosts:
      - host: my.host.local
        paths:
          - path: /
            pathType: Prefix
    ingressClassName: ""
    tls:
      - hosts:
          - my.host.local
        secretName: mycert-tls

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  wine:
    enabled: false
    mountPath: /home/kasm-user/.wine
  cert:
    # -- This image needs cert in PEM format
    # -- If you use cert-manager, you can add it to your certificates :
    # -- https://cert-manager.io/docs/usage/certificate/#additional-certificate-output-formats
    enabled: false
    type: custom
    volumeSpec:
      secret:
        secretName: mycert-tls
    subPath:
      - path: tls-combined.pem
        mountPath: /config/private-cert.pem
        readOnly: true

